To: crypt (at) bis.doc.gov, enc (at) nsa.gov, web_site (at) bis.doc.gov
Cc: Zip-Bugs (at) goatley.com
Subject: TSU NOTIFICATION - Encryption   (Info-ZIP iz_aes_wg.zip)

   SUBMISSION TYPE:       TSU
   SUBMITTED BY:          Edward Gordon
   SUBMITTED FOR:         The Info-ZIP group (an informal, Internet-based
                          collection of software developers with the contact
                          address given in next item)
   POINT OF CONTACT:      Zip-Bugs (at) goatley.com
   PHONE and/or FAX:      n/a
   MANUFACTURER:          n/a
   PRODUCT NAME/MODEL #:  iz_aes_wg
   ECCN:                  5D002

   NOTIFICATION:

           ftp://ftp.info-zip.org/pub/infozip/crypt/iz_aes_wg.zip

