name: Alpine 32-bit

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
        fail-fast: false
        matrix:
          include:

            # GCC Versions on Ubuntu

            - name: i386 + gcc
              os: i386
              compiler: gcc

            - name: amd64 + gcc
              os: amd64
              compiler: gcc

            - name: i386 + clang
              os: i386
              compiler: clang
              packages: clang

            - name: amd64 + gcc
              os: amd64
              compiler: clang
              packages: clang

    container:
      image: ${{ matrix.os }}/alpine

    steps:
      - name: install the Perl, gcc, make & zlib
        run: |
          apk update
          apk add build-base perl perl-dev zlib-dev wget unzip ${{ matrix.packages }}

      - uses: actions/checkout@v1
        with:
            # show-progress: 'false'
            ref: build

      - name: Display gcc version
        run: gcc -v

      - name: fetch iz_aes_wg10.zip
        run: |
          wget -q ftp://ftp.info-zip.org/pub/infozip/src/iz_aes_wg10.zip
          unzip -o iz_aes_wg10.zip

      - name: configure & build (unix/Makefile)
        run: |
          make -f unix/Makefile generic CC=gcc

      - name: Run zip --help
        run: ./zip --help

      - name: Run zip -v
        run: ./zip -v

      - name: Run zipcloak --help
        run: ./zipcloak --help

      - name: Run zipcloak -v
        run: ./zipcloak -v

      - name: Run zipnote --help
        run: ./zipnote --help

      - name: Run zipnote -v
        run: ./zipnote -v

      - name: Run zipsplit --help
        run: ./zipsplit --help

      - name: Run zipsplit -v
        run: ./zipsplit -v
