name: Configure
on: [push, pull_request, workflow_dispatch]
jobs:
  configure:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:

          # GCC Versions on Ubuntu

          - name: Ubuntu + gcc-13
            os: ubuntu-latest
            compiler: gcc-13

          - name: Ubuntu + gcc-12
            os: ubuntu-latest
            compiler: gcc-12

          - name: Ubuntu + gcc-11
            os: ubuntu-latest
            compiler: gcc-11
            packages: gcc-11

          - name: Ubuntu + gcc-10
            os: ubuntu-latest
            compiler: gcc-10

          - name: Ubuntu + gcc-9
            os: ubuntu-latest
            compiler: gcc-9

          - name: Ubuntu + gcc-8
            os: ubuntu-20.04
            compiler: gcc-8
            packages: gcc-8

          - name: Ubuntu + gcc-7
            os: ubuntu-20.04
            compiler: gcc-7
            packages: gcc-7

          # CLANG Versions on Ubuntu

          - name: Ubuntu + clang-15
            os: ubuntu-latest
            compiler: clang-15

          - name: Ubuntu + clang-14
            os: ubuntu-latest
            compiler: clang-14

          - name: Ubuntu + clang-13
            os: ubuntu-latest
            compiler: clang-13

          - name: Ubuntu + clang-12
            os: ubuntu-20.04
            compiler: clang-12

          - name: Ubuntu + clang-11
            os: ubuntu-20.04
            compiler: clang-11

          - name: Ubuntu + clang-10
            os: ubuntu-20.04
            compiler: clang-10

          - name: Ubuntu + clang-9
            os: ubuntu-20.04
            compiler: clang-9
            packages: clang-9

          - name: Ubuntu + clang-8
            os: ubuntu-20.04
            compiler: clang-8
            packages: clang-8

          - name: Ubuntu + clang-7
            os: ubuntu-20.04
            compiler: clang-7
            packages: clang-7

          # GCC Versions on MacOS

          - name: MacOS + gcc-13
            os: macos-latest
            compiler: gcc-13
            # packages: gcc-13

          - name: MacOS + gcc-12
            os: macos-latest
            compiler: gcc-12
            # packages: gcc-12

          - name: MacOS + gcc-11
            os: macos-latest
            compiler: gcc-11
            # packages: gcc-11

          - name: MacOS + gcc-10
            os: macos-11
            compiler: gcc-10

          # clang Versions on MacOS

          - name: MacOS + clang 14
            os: macos-latest
            compiler: clang

          - name: MacOS + clang-13
            os: macos-11
            compiler: clang

        # # CLANG Versions on Windows

        #   - name: Windows + clang
        #     os: windows-latest
        #     compiler: clang

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        ref: build

    - name: Install packages (Ubuntu)
      if: runner.os == 'Linux' && matrix.packages
      run: |
        sudo apt-get update
        sudo apt-get install -y ${{ matrix.packages }}

    - name: fetch iz_aes_wg10.zip
      run: |
        wget ftp://ftp.info-zip.org/pub/infozip/src/iz_aes_wg10.zip
        unzip iz_aes_wg10.zip

    - name: configure & build
      run: |
        make -f unix/Makefile generic CC=${{ matrix.compiler }} ${{ matrix.configure-args }}


    - name: Run zip --help
      run: ./zip --help
      working-directory: ${{ matrix.build-dir }}

    - name: Run zip -v
      run: ./zip -v
      working-directory: ${{ matrix.build-dir }}

    # - name: Upload build errors
    #   uses: actions/upload-artifact@v3
    #   if: failure()
    #   with:
    #     name: ${{ matrix.name }} (configure)
    #     path: |
    #       **/Makefile
    #       ${{ matrix.build-dir || '.' }}/configure.log
    #     retention-days: 30